/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeDirectory(dirPath: string): Array<LanguageStat>

export interface LanguageStat {
  lang: string
  count: number
  ratio: number
  isProgramming: boolean
}
