/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function analyzeDirectory(dirPath: string): Promise<Array<LanguageStat>>

export declare function analyzeDirectorySync(dirPath: string): Array<LanguageStat>

export interface LanguageStat {
  lang: string
  count: number
  bytes: number
  ratio: number
  isProgramming: boolean
}
